[tasks.deps]
cmds = [
  "go mod tidy"
]

[tasks.build]
cmds = [
  "go build -o dist/daylog ./main.go {{.CLI_ARGS}}"
]

[tasks.run]
cmds = [
  "go run main.go {{.CLI_ARGS}}"
]

[tasks.test]
cmds = [
  "go test ./... -race"
]

[tasks.release]
cmds = [
  "git tag {{.CLI_ARGS}}",
  "git push origin --tags",
]
