Output demo.gif

Set FontSize 30
Set Width 1200
Set Height 800

Type "daylog"
Sleep 2s
Enter

Sleep 1s

Type@100ms "o* ate a burrito"
Sleep 1s
Escape
Type@100ms ":wq"
Sleep 1s
Enter

Sleep 2s

Type "daylog show"
Sleep 2s
Enter

Sleep 2s

Type "daylog -- tomorrow"
Sleep 500ms
Enter

Sleep 1s

Type@100ms "o* TODO: get another burrito"
Sleep 1s
Escape
Type@100ms ":wq"
Sleep 1s
Enter

Sleep 2s

Type "daylog show -- tomorrow"
Sleep 2s
Enter

Sleep 5s
