name: test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - uses: actions/setup-homebrew@master
      - run: brew install notnmeyer/tsk/tsk
      - run: tsk test
